WINDOW_WIDTH: int = 1200
WINDOW_HEIGHT: int = 700
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

FPS: int = 60

SHADERS_DIR: str = "../shaders/"

CAMERA_FOV: float = 50  # deg
CAMERA_NEAR: float = 0.1
CAMERA_FAR: float = 100
CAMERA_SPEED: float = 0.01
MOUSE_SENSITIVITY: float = 0.07
